# Generated by Django 4.2.3 on 2023-07-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontacts',
            name='phone_no',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
