# Generated by Django 4.2.3 on 2023-07-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApi', '0003_registereduser_rename_usercontacts_contacts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registereduser',
            name='phone_no',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='spam',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
