# Generated by Django 4.2.3 on 2023-07-16 22:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userApi', '0004_alter_registereduser_phone_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=200)),
                ('phone_no', models.PositiveIntegerField(unique=True)),
                ('email', models.EmailField(blank=True, default='', max_length=100)),
                ('password', models.CharField(max_length=200)),
                ('spam', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='contacts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='RegisteredUser',
        ),
    ]
