# Generated by Django 4.2.3 on 2023-07-16 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userApi', '0005_globaluser_alter_contacts_user_delete_registereduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=200)),
                ('phone_no', models.PositiveIntegerField(unique=True)),
                ('email', models.EmailField(blank=True, default='', max_length=100)),
                ('password', models.CharField(max_length=200)),
                ('spam', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='contacts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApi.registereduser'),
        ),
    ]
