# Generated by Django 4.2.3 on 2023-07-17 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApi', '0006_registereduser_alter_contacts_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='spam',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
