# Generated by Django 4.2.3 on 2023-07-17 04:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApi', '0007_contacts_spam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='phone_no',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='phone_no',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(99999999)]),
        ),
    ]
