# Generated by Django 4.2.3 on 2023-07-16 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=200)),
                ('phone_no', models.PositiveIntegerField(unique=True)),
                ('email', models.EmailField(blank=True, default='', max_length=100)),
                ('password', models.CharField(max_length=200)),
                ('spam', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
